language: julia
os:
    - linux
julia:
    - 0.7
    - 1.0.1

notifications:
    emails:
        recipients:
            - donsadit@gmail.com

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: alway
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(url=pwd())); Pkg.build("SnowballStemmer"); Pkg.test("SnowballStemmer"; coverage=true)';
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("SnowballStemmer")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
